### ISSUE TITLE
fix: UI of chat page should be of full screen till bottom

### ISSUE THREAD

**Issue by krishnaKanta2008** [krishnaKanta2008/Quantica#11]
# Description

The chat section of the chat page is not till the bottom.

# File reproduce

./client/src/components/Chat/Chat.tsx

# screenshots

![image](https://github.com/user-attachments/assets/f3ec8596-4612-4b1c-934d-b8db3d9115bc)
![Screenshot 2024-10-14 194638](https://github.com/user-attachments/assets/88a58db2-034c-4ed7-93ec-47700ce9810d)
![Screenshot 2024-10-14 194622](https://github.com/user-attachments/assets/4b947b13-f119-4349-94f3-3d1c39b7a7d6)
![Screenshot 2024-10-14 194611](https://github.com/user-attachments/assets/b1eefc7f-d607-4deb-9bd5-0ed2af8f9740)

**Comment by deepraj21** [comment]
assign me.

**Comment by krishnaKanta2008** [comment]
ok assigned.
